# ------------------------------------------------------------------------- #
#         ___      ___ ________  ________  ________     ___    ___
#        |\  \    /  /|\   __  \|\   __  \|\   __  \   |\  \  /  /|
#        \ \  \  /  / | \  \|\  \ \  \|\  \ \  \|\  \  \ \  \/  / /
#         \ \  \/  / / \ \   __  \ \   _  _\ \  \\\  \  \ \    / /
#          \ \    / /   \ \  \ \  \ \  \\  \\ \  \\\  \  /     \/
#           \ \__/ /     \ \__\ \__\ \__\\ _\\ \_______\/  /\   \
#            \|__|/       \|__|\|__|\|__|\|__|\|_______/__/ /\ __\
#                                                      |__|/ \|__|
#
# ------------------------------------------------------------------------- #
# VaroX Configuration | Developed by Frostleaf (jozelot_)
# ------------------------------------------------------------------------- #

# ========================================================================= #
#                             0. INFORMATION                                #
# ========================================================================= #

#
#
#


# ========================================================================= #
#                            I. CORE SETTINGS                               #
# ========================================================================= #

# The internal version number of the configuration file.
# DO NOT change this, it is used for plugin compatibility checks.
version: 1.0.0

# The language to be used for all plugin messages (e.g., de or en).
# Make sure the corresponding locale file exists (locales/de.yml).
# Languages availabel: de, en, fr, es, ru
locale: de

# The display name for the Varo event.
varo-name: 'Varo 4'

# The server MOTD (Message of the Day) shown in the multiplayer menu.
server-motd: 'A VaroX Server'

# ========================================================================= #
#                            II. PLAYER SETTINGS                            #
# ========================================================================= #

# Maximum player count mode:
# - DYNAMIC: Calculates Max Slots based on the number of registered teams/players.
# - SET: Uses the fixed value specified below.
# - SERVER: Takes the value from server.properties.
max-player-count-mode: DYNAMIC

# Maximum slots, used when 'max-player-count-mode' is SET.
# NOTE: This is only visual.
max-player-count-set: 100

# Enables start protection.
enable-start-protection: true

# Duration of the start protection in seconds. During this time, players
# cannot attack each other or inflict damage.
start-protection-time: 10 # (Example: 10 seconds)

# ========================================================================= #
#                         III. WORLDBORDER & MAP                            #
# ========================================================================= #

# Activates the dynamic World Border for the Varo event.
# You should enable the WorldBoarder beacause the game would be very lame if everyone are 10k blocks away.
enable-worldboarder: true

# The starting size of the World Border (Radius).
# NOTE: The actual edge is at start_worldboarder_size * 2
# Example: 2000 corresponds to a playing field of 4000x4000 blocks.
start-worldboarder-size: 2000

# The center of the World Border. Usually (0, 0).
center-x: 0
center-z: 0

# World Border Shrink Phases.
# The phases are executed sequentially after the previous phase is complete.
# NOTE: Remember that in the Nether, the World Border shrinks 8 times faster than in the Overworld.
# These are the default phases and you should change them to your likes.
border_phases:
  '1':
    # Delay before this phase starts (in seconds).
    delay_seconds: 60
    # The target size of the World Border after this phase is complete (Radius).
    target_size: 1000
    # Duration of the shrink: How long the reduction to the target_size
    # should take (in seconds).
    duration_seconds: 60
  '2':
    delay_seconds: 60
    target_size: 100
    duration_seconds: 60
  '3':
    delay_seconds: 60
    target_size: 10
    duration_seconds: 60

# ========================================================================= #
#                        IV. BANNED ITEMS & POTIONS                         #
# ========================================================================= #

# A list of items that are neither allowed to be crafted nor used.
# Format: MATERIAL_NAME[:DATA_VALUE] (e.g., 'GOLDEN_APPLE:1' for Enchanted Golden Apple)
banned-items:
  - ENDER_EYE           # Ender Eyes -> No END allowed, should be left as is
  - SKULL:1             # Wither Skeleton Skull -> No Wither Boss
  - GOLDEN_APPLE:1      # Enchanted Golden Apple
  - FISHING_ROD         # Fishing Rod

# A list of potions that are not allowed to be brewed, drunk, or thrown as Splash Potions.
# This uses the Item IDs + Data Values from Spigot/Bukkit.
# The list includes Base, Extended, and Tier II versions (including Splash).
banned-potions:
  # POTIONS CONSIDERED TOO POWERFUL OR TOO ANNOYING

  # POISON
  - '8196'  # Poison I (0:45)
  - '8260'  # Poison I (Extended 2:00)
  - '8228'  # Poison II (1:00)
  - '16388' # Splash Poison I (0:33)
  - '16452' # Splash Poison I (Extended 1:30)
  - '16420' # Splash Poison II (0:45)

  # HARMING (Instant Damage)
  - '8204'  # Harming I (Instant)
  - '8236'  # Harming II (Instant)
  - '16396' # Splash Harming I (Instant)
  - '16428' # Splash Harming II (Instant)

  # POTIONS THAT LEAD TO UNFAIR ADVANTAGES

  # NIGHT VISION
  - '8238'  # Night Vision (3:00)
  - '8262'  # Night Vision (Extended 8:00)
  - '16422' # Splash Night Vision (2:15)
  - '16454' # Splash Night Vision (Extended 6:00)

  # WEAKNESS
  - '8232'  # Weakness (1:30)
  - '8264'  # Weakness (Extended 4:00)
  - '16424' # Splash Weakness (1:07)
  - '16456' # Splash Weakness (Extended 3:00)

  # SLOWNESS
  - '8234'  # Slowness (1:30)
  - '8266'  # Slowness (Extended 4:00)
  - '16426' # Splash Slowness (1:07)
  - '16458' # Splash Slowness (Extended 3:00)