# ------------------------------------------------------------------------- #
#         ___      ___ ________  ________  ________     ___    ___
#        |\  \    /  /|\   __  \|\   __  \|\   __  \   |\  \  /  /|
#        \ \  \  /  / | \  \|\  \ \  \|\  \ \  \|\  \  \ \  \/  / /
#         \ \  \/  / / \ \   __  \ \   _  _\ \  \\\  \  \ \    / /
#          \ \    / /   \ \  \ \  \ \  \\  \\ \  \\\  \  /     \/
#           \ \__/ /     \ \__\ \__\ \__\\ _\\ \_______\/  /\   \
#            \|__|/       \|__|\|__|\|__|\|__|\|_______/__/ /\ __\
#                                                      |__|/ \|__|
#
# ------------------------------------------------------------------------- #
# VaroX Configuration | Developed by Frostleaf (jozelot_)
# ------------------------------------------------------------------------- #

# ========================================================================= #
#                            I. CORE SETTINGS                               #
# ========================================================================= #

# Die interne Versionsnummer der Konfigurationsdatei.
# NICHT ändern, wird zur Kompatibilitätsprüfung des Plugins genutzt.
version: 1.0.0

# Die zu verwendende Sprache für alle Plugin-Nachrichten (z.B. de oder en).
# Stellt sicher, dass die entsprechende Locale-Datei existiert (locales/de.yml).
locale: de

# Der Anzeigename für das Varo-Event.
varo-name: 'Varo 4'

# Der Server-MOTD, der im Multiplayer-Menü angezeigt wird.
server-motd: 'A VaroX Server'

# ========================================================================= #
#                            II. PLAYER SETTINGS                            #
# ========================================================================= #

# Maximale Spieleranzahl-Modus:
# - DYNAMIC: Berechnet Max-Slots aus der Anzahl der registrierten Teams/Spieler.
# - SET: Nutzt den fest eingestellten Wert unten.
# - SERVER: Nimmt den Wert aus der server.propeties
max-player-count-mode: DYNAMIC

# Maximale Slots, wenn 'max-player-count-mode' auf SET steht.
max-player-count-set: 100

# Maximale Slots, wenn 'max-player-count-mode' auf SET steht.
enable-start-protection: true

# Dauer des Startschutzes in Sekunden. Während dieser Zeit können sich Spieler
# nicht gegenseitig angreifen oder Schaden zufügen.
start-protection-time: 10 # (Beispiel: 10 Sekunden)

# ========================================================================= #
#                         III. WORLDBORDER & MAP                            #
# ========================================================================= #

# Aktiviert die dynamische Weltgrenze (WorldBorder) des Varo-Events.
enable-worldboarder: true

# Die Größe des Weltborders zu Beginn des Spiels (Radius).
# ACHTUNG: Der tatsächliche Rand liegt bei start_worldboarder_size * 2
# Beispiel: 2000 entspricht einem Spielfeld von 4000x4000 Blöcken.
start-worldboarder-size: 2000

# Das Zentrum der Weltgrenze. Normalerweise (0, 0).
center-x: 0
center-z: 0

# Phasen der Weltgrenzen-Verkleinerung (Shrink-Phases).
# Die Phasen werden nacheinander ausgeführt, nachdem die vorherige Phase abgeschlossen ist.
# Denk daran, dass im Nether die WorldBoarder 8mal so schnell verkleinert wie in der Overworld
border_phases:
  '1':
    # Phasen der Weltgrenzen-Verkleinerung (Shrink-Phases).
    # Die Phasen werden nacheinander ausgeführt, nachdem die vorherige Phase abgeschlossen ist.
    delay_seconds: 60
    # Die Zielgröße des WorldBorders nach Abschluss dieser Phase (Radius).
    target_size: 1000
    # Dauer der Verkleinerung (Duration): Wie lange die Verkleinerung auf die target_size
    # dauern soll (in Sekunden).
    duration_seconds: 60
  '2':
    delay_seconds: 60
    target_size: 100
    duration_seconds: 60
  '3':
    delay_seconds: 60
    target_size: 10
    duration_seconds: 60

# ========================================================================= #
#                        IV. BANNED ITEMS & POTIONS                         #
# ========================================================================= #

# Eine Liste von Gegenständen, die weder hergestellt noch benutzt werden dürfen.
# Format: MATERIAL_NAME[:DATA_VALUE] (z.B. 'GOLDEN_APPLE:1' für Enchanted Golden Apple)
banned-items:
  - ENDER_EYE           # Enderaugen -> Kein END erlaubt, sollte so gelassen werden
  - SKULL:1             # Witherskelleton Skull -> Keine Wither
  - GOLDEN_APPLE:1      # Verzauberter Goldapfel
  - FISHING_ROD         # Angelrute

# Eine Liste von Tränken, die nicht gebraut, getrunken oder als Splash geworfen werden dürfen.
# Hier werden die Item-IDs + Data-Werte von Spigot/Bukkit verwendet.
# Die Liste enthält Basis-, Extended- und Tier II-Versionen (auch Splash).
banned-potions:
  # TRÄNKE, DIE ALS ZU STARK ODER ZU STÖREND GESEHEN WERDEN

  # GIFT (POISON)
  - '8196'  # Poison I (0:45)
  - '8260'  # Poison I (Extended 2:00)
  - '8228'  # Poison II (1:00)
  - '16388' # Splash Poison I (0:33)
  - '16452' # Splash Poison I (Extended 1:30)
  - '16420' # Splash Poison II (0:45)

  # SCHADEN (HARMING)
  - '8204'  # Harming I (Instant)
  - '8236'  # Harming II (Instant)
  - '16396' # Splash Harming I (Instant)
  - '16428' # Splash Harming II (Instant)

  # TRÄNKE, DIE FÜR UNFAIRE VORTEILE SORGEN

  # SICHTBARKEIT (NIGHT VISION)
  - '8238'  # Night Vision (3:00)
  - '8262'  # Night Vision (Extended 8:00)
  - '16422' # Splash Night Vision (2:15)
  - '16454' # Splash Night Vision (Extended 6:00)

  # SCHWÄCHE (WEAKNESS)
  - '8232'  # Weakness (1:30)
  - '8264'  # Weakness (Extended 4:00)
  - '16424' # Splash Weakness (1:07)
  - '16456' # Splash Weakness (Extended 3:00)

  # LANGSAMKEIT (SLOWNESS)
  - '8234'  # Slowness (1:30)
  - '8266'  # Slowness (Extended 4:00)
  - '16426' # Splash Slowness (1:07)
  - '16458' # Splash Slowness (Extended 3:00)